import { ArrowUpRight, Award, BriefcaseBusiness, Check, GraduationCap, Sparkles } from "lucide-react";
import SiteNav from "@/components/SiteNav";
import { cvUrl, journeyStops, portraitUrl } from "@/lib/portfolioData";

export default function About() {
  return <main className="site-shell inner-page"><SiteNav /><div className="page-wrap page-hero"><div><div className="section-index">01 / ABOUT ME</div><h1>Meet the person<br /><em>behind the work.</em></h1></div><p>Computer science student. Creative builder. Curious about the space where technology becomes something people can feel.</p></div>
    <section className="page-wrap about-grid"><div className="about-photo"><img src={portraitUrl} alt="Jaya Kaushiki" /><div className="photo-label">JAYA / BANGALORE</div></div><div className="about-copy"><div className="about-kicker"><Sparkles size={17} /> A short version</div><h2>Thoughtful by<br /><em>default.</em></h2><p>I’m Jaya Kaushiki, a computer science student at Manipal Institute of Technology, Bangalore. I like turning blank canvases into clear, warm, and useful digital experiences.</p><p>My current interests sit between front-end development, UI/UX, and AI-assisted workflows. I learn by making — then I refine until the experience feels simple, intentional, and a little bit delightful.</p><a className="primary-button" href={cvUrl} target="_blank" rel="noreferrer">Open my CV <ArrowUpRight size={16} /></a></div></section>
    <section className="page-wrap journey-page"><div className="section-index">02 / THE JOURNEY</div><h2>The stops that<br /><em>shaped me.</em></h2><div className="journey-list">{journeyStops.map((stop, i) => <article key={stop.id} className="journey-row"><div className="journey-number">0{i + 1}</div><div><div className="journey-year">{stop.year}</div><h3>{stop.label}</h3><p>{stop.body}</p></div></article>)}</div></section>
    <section className="page-wrap about-proof"><div className="proof-item"><GraduationCap size={20} /><span>EDUCATION</span><strong>MIT, Bangalore</strong></div><div className="proof-item"><BriefcaseBusiness size={20} /><span>LEADERSHIP</span><strong>General Secretary, Graphica</strong></div><div className="proof-item"><Award size={20} /><span>CERTIFICATIONS</span><strong>Gemini AI + Figma UI/UX</strong></div></section>
    <footer className="site-footer page-wrap"><span>© 2026 JAYA KAUSHIKI</span><a href="/builds" target="_blank" rel="noreferrer">NEXT / BUILDS <ArrowUpRight size={14} /></a></footer>
  </main>;
}
